server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/users/**

        - id: RATING-MICROSERVICE
          uri: lb://RATING-MICROSERVICE
          predicates:
            - Path=/ratings/**

        - id: HOTEL-MICROSERVICE
          uri: lb://HOTEL-MICROSERVICE
          predicates:
            - Path=/hotels/**, /staffs/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-wth-eureka: true
    service-url:
      defaulZone: http://localhost:8761/eureka


#OKTA configuration for api gateway
okta:
  oauth2:
    issuer: https://dev-27478692.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa9jcf1n8J4C9tkH5d7
    client-secret: 4Rw5Nr-4IxUnsIY8ZkQg3FcdsRWvxxsUvPbmR1PW
    scopes: openid, profile, email, offline_access