server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: emad
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: HOTEL-MICROSERVICE

eureka:
  instance:
    prefer-ip-address: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-27478692.okta.com/oauth2/default
    audience: api://default